# Generated by Django 5.0.4 on 2024-04-16 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scayt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="age_groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("U21", "U21"),
                        ("U18", "U18"),
                        ("U16", "U16"),
                        ("U15", "U15"),
                        ("U14", "U14"),
                        ("U12", "U12"),
                    ],
                    max_length=3,
                ),
                default=[],
                size=6,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="round_family",
            field=models.CharField(
                choices=[
                    ("bristol", "York/Hereford/Bristols"),
                    ("metric", "Metrics"),
                    ("720", "720s"),
                    ("720/H2H", "720/H2H"),
                    ("windsor", "St George/Albion/Windsors"),
                    ("windsor", "Westerns"),
                ],
                default="720",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
