# Generated by Django 5.0.4 on 2024-04-16 11:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scayt", "0002_event_age_groups_event_round_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(default="2024-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="age_groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("U21", "U21"),
                        ("U18", "U18"),
                        ("U16", "U16"),
                        ("U15", "U15"),
                        ("U14", "U14"),
                        ("U12", "U12"),
                    ],
                    max_length=3,
                ),
                default=["U21", "U18", "U16", "U15", "U14", "U12"],
                help_text="Entry a comma separated list of age groups - U21,U18,U16,U15,U14,U12",
                size=6,
            ),
        ),
    ]
