# Generated by Django 5.0.4 on 2025-02-21 10:06

import django.contrib.postgres.fields
import scayt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scayt", "0003_event_date_alter_event_age_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venue",
            options={"ordering": ["host_club_name"]},
        ),
        migrations.AlterField(
            model_name="event",
            name="age_groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("U21", "U21"),
                        ("U18", "U18"),
                        ("U16", "U16"),
                        ("U15", "U15"),
                        ("U14", "U14"),
                        ("U12", "U12"),
                    ],
                    max_length=3,
                ),
                default=scayt.models.default_age_groups,
                help_text="\n            Entry a comma separated list of age groups -\n            U21,U18,U16,U15,U14,U12\n        ",
                size=6,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="round_family",
            field=models.CharField(
                choices=[
                    ("bristol", "York/Hereford/Bristols"),
                    ("metric", "1440s/Metrics"),
                    ("720", "720s"),
                    ("720/H2H", "720s/H2H"),
                    ("windsor", "St George/Albion/Windsors"),
                    ("western", "Westerns"),
                ],
                max_length=10,
            ),
        ),
    ]
