# Generated by Django 5.0.4 on 2025-03-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scayt", "0004_copy_tweaks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="round_family",
            field=models.CharField(
                choices=[
                    ("bristol", "York/Hereford/Bristols"),
                    ("metric", "1440s/Metrics"),
                    ("720", "720s"),
                    ("720/H2H", "720s/H2H"),
                    ("s-metric", "Short Metrics"),
                    ("windsor", "St George/Albion/Windsors"),
                    ("western", "Westerns"),
                ],
                max_length=10,
            ),
        ),
    ]
