# Generated by Django 5.2.12 on 2026-04-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scayt", "0010_alter_event_round_family"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="round_family",
            field=models.CharField(
                choices=[
                    ("bristol", "York/Hereford/Bristols"),
                    ("metric", "1440s/Metrics"),
                    ("720", "720s"),
                    ("720/H2H", "720s/H2H"),
                    ("900", "900s"),
                    ("l-metric", "Long Metrics"),
                    ("s-metric", "Short Metrics"),
                    ("windsor", "St George/Albion/Windsors"),
                    ("western", "Westerns"),
                    ("national", "Nationals"),
                ],
                max_length=10,
            ),
        ),
    ]
